apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  url: https://istio-release.storage.googleapis.com/charts
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  releaseName: istio-base
  targetNamespace: istio-system
  chart:
    spec:
      chart: base
      version: "1.24"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  install:
    createNamespace: true
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: flux-system
spec:
  releaseName: istiod
  targetNamespace: istio-system
  chart:
    spec:
      chart: istiod
      version: "1.24"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: "ambient"
  dependsOn:
    - name: istio-base
      namespace: flux-system
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-cni
  namespace: flux-system
spec:
  releaseName: istio-cni
  targetNamespace: istio-system
  chart:
    spec:
      chart: cni
      version: "1.24"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  values:
    profile: "ambient"
  dependsOn:
    - name: istiod
      namespace: flux-system
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-ztunnel
  namespace: flux-system
spec:
  releaseName: istio-ztunnel
  targetNamespace: istio-system
  chart:
    spec:
      chart: ztunnel
      version: "1.24"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  dependsOn:
    - name: istiod
      namespace: flux-system
  interval: 1h