apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-demo-shared-staging
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./manifests
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: gitops-demo-shared-staging
  timeout: 60m0s
  wait: true