name: Deploy EKS Cluster
on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-24.04
        defaults:
            run:
                shell: bash
                working-directory: cdk
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Get pnpm store directory
              id: pnpm-cache
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - name: Cache pnpm dependencies
              uses: actions/cache@v3
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: "Install dependencies with pnpm"
              run: pnpm install

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ vars.AWS_REGION }}

            - name: CDK Deploy
              env:
                  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
                  AWS_VPC_ID: ${{ secrets.AWS_VPC_ID }}
                  AWS_REGION: ${{ vars.AWS_REGION }}
              run: pnpm deploy:eks:shared
